/*
 * This source file was generated by the Gradle 'init' task
 */

package com.example.project;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest
{
    @Test void appHasAGreeting()
    {
        App classUnderTest = new App();
        assertAll(  () -> assertNotNull( classUnderTest.getGreeting(), "app should have a greeting" )
                  , () -> assertEquals( "Hello World!", classUnderTest.getGreeting() )

        );
    }
}
